language: python
python:
    - "3.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false

addons:
  apt:
    packages: lcov

cache:
    directories:
        - "~/.platformio"
        - $HOME/.cache/pip

install:
    - pip install -U platformio
    - pip install -U cpp-coveralls
    - platformio lib -g install https://github.com/bblanchon/ArduinoJson
    - platformio lib -g install https://github.com/pololu/vl53l0x-arduino
    - platformio lib -g install https://github.com/madhephaestus/ESP32Servo
    - platformio lib -g install https://github.com/pkerspe/ESP-FlexyStepper
    - platformio lib -g install https://github.com/me-no-dev/AsyncTCP
    - platformio lib -g install https://github.com/me-no-dev/ESPAsyncWebServer

script:
     - pio run -e esp32doit-devkit-v1

after_success:
# Create lcov report
- lcov --capture --directory . --output-file coverage.info
- lcov --remove coverage.info '/usr/*' --output-file coverage.info # filter system-files
- lcov --list coverage.info # debug info
# Uploading report to CodeCov
- bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"


