language: python
python:
    - "3.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false

env:
    - PLATFORMIO_CI_SRC=ROBOT_GAS_MAPPING/lib/ESP-FlexyStepper/src/ESP-FlexyStepper.h
    - PLATFORMIO_CI_SRC=ROBOT_GAS_MAPPING/lib/AsyncTCP/src/AsyncTCP.h
    - PLATFORMIO_CI_SRC=ROBOT_GAS_MAPPING/lib/MPU6050/MPU6050.h
    - PLATFORMIO_CI_SRC=ROBOT_GAS_MAPPING/lib/I2Cdev/I2Cdev.h
cache:
    directories:
        - "~/.platformio"
        - $HOME/.cache/pip

install:
    - pip install -U platformio
    - pio update
    - platformio lib -g install https://github.com/espressif/arduino-esp32
    - platformio lib -g install https://github.com/bblanchon/ArduinoJson
    - platformio lib -g install https://github.com/pololu/vl53l0x-arduino
    - platformio lib -g install https://github.com/madhephaestus/ESP32Servo

script:
    -  - pio ci --lib="." --board=esp32doit-devkit-v1
